name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Main Server
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/backend/
            pm2 stop youniversity-backend
            git checkout main
            git pull
            yarn install --immutable
            pm2 start youniversity-backend
            sleep 10
            pm2 logs youniversity-backend --nostream --out --lines 30
            pm2 logs youniversity-backend --nostream --err --lines 30
